services:
  ws_client:
    build: ../../nodes/websocket_client
    environment:
      WS_URL: http://127.0.0.1:8123 #see websocket_relay_server
      TX_PORT: 80
      RX_HOST: http://cli
  
  cli:
    build: ../../nodes/cli_client
    environment:
      TX_HOST: http://ws_client
      RX_PORT: 80